Use clap derive macros
msfjarvis/healthchecks-rs pull request #7
Opened 2020-11-03 15:09 UTC by Skrilltrax

2020-11-03 16:43 UTC, msfjarvis requested changes
The code in `monitor/` also needs to be migrated.

2020-11-03 16:43 UTC, msfjarvis commented on hcctl/src/main.rs
> +#[clap(version = env ! ("CARGO_PKG_VERSION"))]
What is this formatting o_O

2020-11-03 16:43 UTC, msfjarvis commented on hcctl/Cargo.toml
> +clap = "3.0.0-beta.2"
Don't do that, just turn on the `derive` feature instead.

2020-11-03 16:46 UTC, Skrilltrax commented
@msfjarvis yeah this was just a test to get initial feedback, will update monitor too.

2020-11-03 16:47 UTC, Skrilltrax commented on hcctl/src/main.rs
> +#[clap(version = env ! ("CARGO_PKG_VERSION"))]
Idk why CLion is doing that

2020-11-04 19:07 UTC, msfjarvis commented on hcctl/Cargo.toml
> +clap = "3.0.0-beta.2"
The default features adds `cargo` which has the `crate_version!()` macro so this can stay as-is

2020-11-04 19:20 UTC, msfjarvis approved these changes

2020-11-04 19:22 UTC, merged